import Head from "next/head"
import Banner from "../components/Banner"
import Header from "../components/Header"
import LargeCard from "../components/LargeCard"
import MediumCard from "../components/MediumCard"
import SmallCard from "../components/SmallCard"

export default function Home({ exploreData, cardsData }) {
	return (
		<div>
			<Head>
				<title>Teguh Airbnb</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<Banner />

			<main className="max-w-7xl mx-auto px-8 md:px-16">
				<section className="pt-6">
					<h2 className="text-2xl font-semibold">Explore Nearby</h2>
					<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
						{exploreData?.map((item) => (
							<SmallCard
								key={item.img}
								img={item.img}
								distance={item.distance}
								location={item.location}
							/>
						))}
					</div>
				</section>

				<section>
					<h2 className="text-2xl font-semibold py-6">Live Anywhere</h2>
					<div className="flex space-x-3 overflow-x-scroll scrollbar-hide p-3">
						{cardsData?.map((item) => (
							<MediumCard key={item.img} img={item.img} title={item.title} />
						))}
					</div>
				</section>

				<LargeCard
					img="https://links.papareact.com/4cj"
					title="The Greatest Outdoors"
					description="Wishlist created by Airbnb"
					buttonText="Get Inspired"
				/>
			</main>
		</div>
	)
}

export async function getStaticProps() {
	const exploreData = await fetch("https://links.papareact.com/pyp").then(
		(res) => res.json()
	)

	const cardsData = await fetch("https://links.papareact.com/zp1").then((res) =>
		res.json()
	)

	return {
		props: {
			exploreData,
			cardsData,
		},
	}
}
