import Head from "next/head"
import Banner from "../components/Banner"
import Header from "../components/Header"

export default function Home({ exploreData }) {
	return (
		<div>
			<Head>
				<title>Teguh Airbnb</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<Banner />

			<main className="max-w-7xl mx-auto px-8 md:px-16">
				<section className="pt-6">
					<h2 className="text-2xl font-semibold">Explore Nearby</h2>

					{/* Pull data from a server - API Endpoint */}
					{exploreData?.map((item) => (
						<h1>{item.location}</h1>
					))}
				</section>
			</main>
		</div>
	)
}

export async function getStaticProps() {
	const exploreData = await fetch("https://links.papareact.com/pyp").then(
		(res) => res.json()
	)

	return {
		props: {
			exploreData,
		},
	}
}
